export const FAENA_ATTENDANCE_PERSONAS_PAGE_SIZE = 100;
export const FAENA_ATTENDANCE_SAVE_FEEDBACK_TIMEOUT = 2200;
export const FAENA_ATTENDANCE_DESKTOP_ROW_HEIGHT = 96;
export const FAENA_ATTENDANCE_DESKTOP_TABLE_HEIGHT = 560;
export const FAENA_ATTENDANCE_MOBILE_CARD_HEIGHT = 208;
export const FAENA_ATTENDANCE_MOBILE_LIST_HEIGHT = 560;
export const FAENA_ATTENDANCE_VIRTUAL_OVERSCAN = 8;
