export type FaenaParticipacionApiShape = {
  idFaenaParticipacion?: number | string;
  id_faena_participacion?: number | string;
  idTenant?: number | string;
  id_tenant?: number | string;
  idFaena?: number | string;
  id_faena?: number | string;
  idPersona?: number | string;
  id_persona?: number | string;
  estado?: 'PENDIENTE' | 'ASISTIO' | 'TARDE' | 'FALTO' | 'JUSTIFICADO';
  horaLlegada?: string | null;
  hora_llegada?: string | null;
  cantPersonasExtra?: number;
  cant_personas_extra?: number;
  multaGenerada?: boolean;
  multa_generada?: boolean;
  montoMulta?: number | null;
  monto_multa?: number | null;
  observaciones?: string | null;
  createdAt?: string;
  created_at?: string;
  createdByUser?: number | string | null;
  created_by_user?: number | string | null;
  updatedAt?: string | null;
  updated_at?: string | null;
  updatedByUser?: number | string | null;
  updated_by_user?: number | string | null;
  anulado?: boolean;
  anuladoAt?: string | null;
  anulado_at?: string | null;
  anuladoByUser?: number | string | null;
  anulado_by_user?: number | string | null;
  motivoAnulacion?: string | null;
  motivo_anulacion?: string | null;
};
