import type { AsistenciaAsambleaEstado } from '../types';

export type AsambleaAttendanceApiShape = {
  idAsistencia?: number | string;
  id_asistencia?: number | string;
  idTenant?: number | string;
  id_tenant?: number | string;
  idAsamblea?: number | string;
  id_asamblea?: number | string;
  idPersona?: number | string;
  id_persona?: number | string;
  estado?: AsistenciaAsambleaEstado;
  horaLlegada?: string | null;
  hora_llegada?: string | null;
  esPadronadoEnMomento?: boolean;
  es_padronado_en_momento?: boolean;
  tieneDerechoVoto?: boolean | null;
  tiene_derecho_voto?: boolean | null;
  votoEmitido?: boolean | null;
  voto_emitido?: boolean | null;
  observaciones?: string | null;
  createdAt?: string;
  created_at?: string;
  createdByUser?: number | string | null;
  created_by_user?: number | string | null;
  updatedAt?: string | null;
  updated_at?: string | null;
  updatedByUser?: number | string | null;
  updated_by_user?: number | string | null;
  anulado?: boolean;
  anuladoAt?: string | null;
  anulado_at?: string | null;
  anuladoByUser?: number | string | null;
  anulado_by_user?: number | string | null;
  motivoAnulacion?: string | null;
  motivo_anulacion?: string | null;
};
